export const books = [
  {
    title: 'Ready Player One',
    author: 'Alan Morg',
    year_of_publication: 2012,
    categoryId: 3,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Silence: Picador Classic',
    author: 'John Morn',
    year_of_publication: 2015,
    categoryId: 2,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Six of Crows: Book 1',
    author: 'Alan Mhen',
    year_of_publication: 2022,
    categoryId: 4,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title:
      "Slaughterhouse 5: The Children's Crusade A Duty-Dance With Death",
    author: 'Julian Mendez',
    year_of_publication: 2022,
    categoryId: 8,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Slaughter House Five',
    author: 'Mayra lown',
    year_of_publication: 2003,
    categoryId: 4,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Snap Judgment',
    author: 'Ivan Isaii',
    year_of_publication: 2002,
    categoryId: 5,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Strange the Dreamer',
    author: 'David Murillo',
    year_of_publication: 2013,
    categoryId: 6,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: "Taduno's Song",
    author: 'Jessica Morr',
    year_of_publication: 2016,
    categoryId: 7,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Terms of Use',
    author: 'Jose Aguirre',
    year_of_publication: 1999,
    categoryId: 2,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'The Age of Daredevils',
    author: 'Moises Lopez',
    year_of_publication: 1998,
    categoryId: 1,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'The Stolen Heir',
    author: 'David Smith',
    year_of_publication: 2000,
    categoryId: 1,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'It Starts with Us: A Novel',
    author: 'Miguel Mora',
    year_of_publication: 2011,
    categoryId: 3,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'The Ballad of Never After',
    author: 'Sulvan Mith',
    year_of_publication: 2009,
    categoryId: 8,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: 'Happy Place',
    author: 'Josh Favel',
    year_of_publication: 2012,
    categoryId: 7,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
  {
    title: "I'm Glad My Mom Died",
    author: 'Luna Cruz',
    year_of_publication: 1998,
    categoryId: 2,
    cover_image: '',
    isActive: true,
    isAvailable: true,
  },
];
